dist: trusty
os: windows
sudo: false
language: cpp
#compiler: gcc

before_install:
  - choco install visualstudio2017buildtools
  - choco install visualstudio2017-workload-vctools
  - eval "${MATRIX_EVAL}"
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
  - echo "Creating build directory..."
  - mkdir build
  - cd build
# - ../cmake-3.5.2-Linux-x86_64/bin/cmake .. -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
  - cmake .. -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
  - cmake --build .
  - ctest --output-on-failure


 env:
  - MATRIX_EVAL="C_COMPILER=cl && CXX_COMPILER=cl"

after_script:
  - echo "Finished script..."

after_success:
  - echo "Congratulations, you didn't fuck up"

after_failure:
  - echo "Build failed. See above for errors"
