os: linux
sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./TravisTest

after_install: